### ISSUE TITLE
Error two parameter forwardRef ( Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter )

### ISSUE THREAD

**Issue by mohammad-moa** [MDBossss/HotelHub#10]
In the OfferLarge component, forwardRef is used, which requires two parameters, one is props and the other is ref, where the value of mapRef is sent as props.
I don't think forwardRef is needed here

``` jsx
const OfferLarge = ({ offer, offerRef, mapRef, setSelectedOfferID }: Props) => {
  // code
}
```

**Comment by MDBossss** [comment]
Yes, thank you for opening this issue. `forwardRef` was not needed here.
